version: "3"

volumes:
  database_data:
      driver: local

services:
  database:
    hostname: gallery
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_NAME=gallery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-alpine
  backend:
    hostname: gallery
    restart: always
    volumes:
      - ./gallery:/api/gallery
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY="django-insecure-_gl#873^qj90cdc27c1gkbliesm@5b9ila2xgcz_5f8+$m574w"
      - DEBUG=true
      - ALLOWED_HOSTS=*

      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=gallery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
    links:
      - database
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 gallery.wsgi"
    # Native server:
    # command: python manage.py runserver 0.0.0.0:8000